apiVersion: v1
kind: Pod
metadata:
  name: color-api-prod
  labels:
    app: color-api
spec:
  containers:
    - name: color-api-prod
      image: lmacademy/color-api:1.2.0
      ports:
        - containerPort: 80
      env:
        - name: DELAY_STARTUP
          value: 'false'
      resources:
        limits:
          cpu: '1'
          memory: '1Gi'
      startupProbe:
        httpGet:
          path: /health
          port: 80
        failureThreshold: 3
        periodSeconds: 5
