apiVersion: v1
kind: Namespace
metadata:
  name: dev
  labels:
    name: dev
---
apiVersion: v1
kind: ResourceQuota
metadata:
  namespace: dev
  name: dev-quota
spec:
  hard:
    requests.cpu: '1' # "1m" is 1 milliCPU, "1" is 1 CPU
    requests.memory: '1Gi'
    limits.cpu: '2'
    limits.memory: '2Gi'
