apiVersion: v1
kind: Namespace
metadata:
  name: prod
  labels:
    name: prod
---
apiVersion: v1
kind: ResourceQuota
metadata:
  namespace: prod
  name: prod-quota
spec:
  hard:
    requests.cpu: '2' # "1m" is 1 milliCPU, "1" is 1 CPU
    requests.memory: '2Gi'
    limits.cpu: '2'
    limits.memory: '2Gi'
