apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx
  annotations:
    description: 'Nginx pod for learning purposes'
spec:
  containers:
    - image: nginx:1.27.0
      name: nginx-container
      ports:
        - containerPort: 80

--- # -> Separator for multiple resources in a single YAML file
# For documentation
# kubectl run nginx-pod --type=NodePort --port=80

apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  labels:
    app: nginx
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: nginx
