apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: demo-ss
spec:
  serverName: busybox
  replicas: 3
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: local-volume-pod
    spec:
      containers:
        - name: local-volume
          image: busybox:1.36.1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-volume-claim
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage

---
apiVersion: v1
kind: Pod
metadata:
  name: local-volume-pod
  labels:
    app: local-volume-pod
